# Generated by Django 5.2.7 on 2025-10-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessStudio', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
    ]
