# Generated by Django 5.2.7 on 2025-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessStudio', '0003_remove_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Photo'),
        ),
    ]
