# Generated by Django 5.2.7 on 2025-10-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessStudio', '0004_alter_trainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_club',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_clubs', to='FitnessStudio.club'),
        ),
        migrations.AlterField(
            model_name='trainer_club',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_clubs', to='FitnessStudio.trainer'),
        ),
    ]
